sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t seol1999/study-docker-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true seol1999/study-docker-kubernetes npm run test
